### ISSUE TITLE
BottomNavigationBar is redrawn when moving between home screen destinations

### ISSUE THREAD

**Issue by msfjarvis** [static-var/vlr-gg#112]
When navigating between destinations on the main screen the bottom bar is redrawn for each destination, which should not be the case.

Passing in `NavState` as an input is causing the unnecessary recomposition when you can lean on AndroidX `NavController` to figure out the currently active destination and pass around inputs like selected/unselected icon using a holder class like [this](https://github.com/msfjarvis/compose-lobsters/blob/61fabc7b35663653dca667f65a822821659b52ad/android/src/main/kotlin/dev/msfjarvis/claw/android/ui/decorations/ClawNavigationBar.kt#L60-L66).

**Comment by static-var** [comment]
Should be fixed here
https://github.com/static-var/vlr-gg/commit/da4d738681c7abc10968b30e118b7f90d5097369

**Comment by msfjarvis** [comment]
It's fixed
