### ISSUE TITLE
Navigation color is incorrect in rankings tab 

### ISSUE THREAD

**Issue by msfjarvis** [static-var/vlr-gg#159]
It seems to be using the background color rather than the bottombar color.

**Comment by static-var** [comment]
Can you tell me which version of the app are you using and if you are using light theme or dark theme on the device? 
The recent versions the app are using variation of the background color, not exactly the background color tho.

**Comment by msfjarvis** [comment]
I'm on v0.2.11 from the Play Store, the problem exists on both dark and light mode.

![screenshot-20220815-191539](https://user-images.githubusercontent.com/13348378/184647447-b8f49da6-3b65-46c4-8247-f591e5c81c0d.png)

![screenshot-20220815-191542](https://user-images.githubusercontent.com/13348378/184647443-d0867f47-5cda-4555-bba3-97d136f890af.png)

**Comment by static-var** [comment]
Probably because of this https://github.com/static-var/vlr-gg/blob/trunk/app/src/main/java/dev/staticvar/vlr/ui/helper/VlrNavBar.kt#L21

But I'll remove it in upcoming release, so it should be okay then.

**Comment by static-var** [comment]
Can you check the latest update on play store and see if the issue is resolved?

**Comment by msfjarvis** [comment]
The colors are consistent on v0.2.12
